-- AlterTable
ALTER TABLE "Building" ADD COLUMN     "latitude" DOUBLE PRECISION NOT NULL DEFAULT 34.0689,
ADD COLUMN     "longitude" DOUBLE PRECISION NOT NULL DEFAULT -118.4452;

-- AlterTable
ALTER TABLE "Review" ADD COLUMN     "downvotes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "upvotes" INTEGER NOT NULL DEFAULT 0;
